apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: a-python-library
    description: A Python Library
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: Ayushsaini20/new_migration

    tags:
        - python
    links:
        - url: https://admin.example-org.com
          title: Admin Dashboard
          icon: dashboard
          type: admin-dashboard
spec:
    type: service
    lifecycle: production
    owner: idpadmins
    system: project-x

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
    name: project-x
    description: Handy tools to keep artists in the loop
spec:
    owner: artist-relations-team
    domain: artists


---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: yaml-check
  description: A repository to build and deploy applications using GitHub Actions and JFrog.
  annotations:
    github.com/project-slug: Ayushsaini20/yaml_check
    github.com/workflows: build.yml
    jenkins.io/job-full-name: yaml_check/build  # Optional if you use Jenkins
  tags:
    - github-actions
    - jfrog
spec:
  type: service
  lifecycle: production
  owner: ayushsaini20

