apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-repo-fetcher
  title: New Fetch GitHub Repository
  description: Fetch and display a GitHub repository dynamically in Backstage
spec:
  owner: backstage-team
  type: service

  parameters:
    - title: GitHub Repository Details
      required:
        - repo
      properties:
        repo:
          type: string
          title: GitHub Repo (owner/repo-name)
          description: Enter GitHub repository in the format `owner/repo-name`
          pattern: '^[a-zA-Z0-9_.-]+/[a-zA-Z0-9_.-]+$'

  steps:
    - id: register-repo
      name: Register GitHub Repository in Backstage
      action: catalog:register
      input:
        repoContentsUrl: https://github.com/${{ parameters.repo }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: View in Backstage Catalog
        url: /catalog/default/component/${{ parameters.repo }}
