apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fetch-git-repo
  title: Fetch Git Repository
  description: Clone a Git repository and use it in Backstage.

spec:
  owner: backstage-team
  type: service

  parameters:
    - title: Git Repository Details
      required:
        - repo_url
        - branch
      properties:
        repo_url:
          type: string
          title: Repository URL
          description: Git repository URL (GitHub, GitLab, Bitbucket, Azure)
        branch:
          type: string
          title: Branch/Tag
          description: Specify branch or tag to checkout

  steps:
    - id: fetch-repository
      name: Fetch Git Repository
      action: fetch:plain
      input:
        url: ${{ parameters.repo_url }}
        branch: ${{ parameters.branch }}
        targetPath: ./repo-code  # Where the repo will be cloned

  output:
    links:
      - title: View Repository
        url: ${{ parameters.repo_url }}
