#alshd
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fetch-github-repo
  title: Register Any GitHub Repository
  description: Dynamically fetch and register any GitHub repository in Backstage.
spec:
  owner: backstage-team
  type: service

  parameters:
    - title: GitHub Repository Details
      required:
        - repo_owner
        - repo_name
      properties:
        repo_owner:
          type: string
          title: Repository Owner
          description: GitHub username or organization (e.g., Ayushsaini20).
        repo_name:
          type: string
          title: Repository Name
          description: The repository to fetch (e.g., yaml_check).

  steps:
    - id: check-catalog-file
      name: Check if catalog-info.yaml exists
      action: fetch:plain
      input:
        url: "https://api.github.com/repos/${{ parameters.repo_owner }}/${{ parameters.repo_name }}/contents/catalog-info.yaml"
        method: GET
        headers:
          Authorization: "Bearer ${GITHUB_TOKEN}"
      if: "{{ output.check-catalog-file.status_code == 404 }}"  # If file is not found

    - id: create-catalog-file
      name: Create catalog-info.yaml
      action: fetch:plain
      input:
        url: "https://api.github.com/repos/${{ parameters.repo_owner }}/${{ parameters.repo_name }}/contents/catalog-info.yaml"
        method: PUT
        headers:
          Authorization: "Bearer ${GITHUB_TOKEN}"
        body:
          message: "Add catalog-info.yaml for Backstage registration"
          content: "{{ base64Encode('apiVersion: backstage.io/v1alpha1\nkind: Component\nmetadata:\n  name: ${{ parameters.repo_name }}\n  description: Automatically generated catalog-info.yaml\nspec:\n  type: service\n  lifecycle: production\n  owner: backstage-team') }}"
          branch: main
      if: "{{ output.check-catalog-file.status_code == 404 }}"

    - id: register-repo
      name: Register GitHub Repository
      action: catalog:register
      input:
        catalogInfoUrl: "https://github.com/${{ parameters.repo_owner }}/${{ parameters.repo_name }}/blob/main/catalog-info.yaml"

  output:
    links:
      - title: View in Backstage
        url: /catalog/default/component/${{ parameters.repo_name }}
