apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service_with_docs
  description: Retrieve artist details
  annotations:
    backstage.io/techdocs-ref: dir.
    github.com/project-slug: Ayushsaini20/new_migration
spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
  
